alias lods="~/Documents/GitHub/my-go-cli/main"
alias zshconfig="vim ~/.zshrc"
alias kittyconfig="vim ~/.config/kitty/kitty.conf"
alias apply="source ~/.zshrc"
alias vim="nvim"
alias .files="cd $DOT_FILES_DIR"
