alias lods="$HOME/Documents/GitHub/my-go-cli/main"
alias zshconfig="vim $HOME/.zshrc"
alias kittyconfig="vim $HOME/.config/kitty/kitty.conf"
alias apply="source $HOME/.zshrc"
alias vim="nvim"
alias .files="cd $DOT_FILES_DIR"
alias copy="xclip -selection c"
