import = [
  "/home/luisotaviodesimone/.files/.config/alacritty/OneDark.toml"
]

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "k",  mods = "Control|Shift", action = "ScrollLineUp" },
  { key = "j",  mods = "Control|Shift", action = "ScrollLineDown" },
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[window]
opacity = 1.00
