[tools]
ansible = "latest"
ansible-core = "latest"
bun = "latest"
fzf = "latest"
glab = "latest"
helm = "latest"
kubecolor = "latest"
lazygit = "latest"
opencode = "latest"
pipx = "latest"
redis = "latest"
usage = "latest"
uv = "latest"
yarn = "1.22.22"
nodejs = "24.11.1"
"github-cli" = "latest"
aws-cli = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
